import { ArrowRight, Eye, HeartHandshake, Target } from "lucide-react";
import { useNavigate } from "react-router-dom";

const hero = "https://images.pexels.com/photos/37811241/pexels-photo-37811241.jpeg?auto=compress&cs=tinysrgb&w=1800";

export default function About() {
  const navigate = useNavigate();
  return <>
    <section className="relative min-h-[70vh] overflow-hidden bg-slate-950 text-white"><img src={hero} alt="Global education environment" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-950/55 to-slate-950/10"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/65 to-transparent"/><div className="relative mx-auto flex min-h-[70vh] max-w-7xl items-end px-4 pb-12 pt-20 sm:px-6 lg:px-8 lg:pb-16"><div className="max-w-3xl reveal-up"><p className="text-[10px] font-black tracking-[.3em] text-cyan-300">ABOUT MEDORA</p><h1 className="mt-4 text-5xl font-black leading-[.96] tracking-[-.04em] sm:text-6xl lg:text-7xl">A more thoughtful way to learn online.</h1><p className="mt-6 max-w-2xl text-sm leading-7 text-white/75 sm:text-base">We combine personal teaching, structured practice and continuous mentoring so learning becomes clearer, calmer and more consistent.</p></div></div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-3">{[[Eye,'Look','Understand the learner before choosing the method.'],[Target,'Understand','Build the right plan around goals, curriculum and pace.'],[HeartHandshake,'Master','Review, practise and improve until progress becomes consistent.']].map(([Icon,title,text]) => <article key={title} className="rounded-[30px] border border-slate-100 bg-slate-50 p-7 shadow-card transition hover:-translate-y-1"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Icon size={22}/></div><h2 className="mt-6 text-2xl font-black text-slate-950">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p></article>)}</div><div className="mt-10 rounded-[34px] bg-gradient-to-r from-blue-700 to-violet-600 p-8 text-white sm:p-10"><p className="text-[10px] font-black tracking-[.25em] text-white/70">OUR PHILOSOPHY</p><h2 className="mt-3 text-4xl font-black">LOOK • UNDERSTAND • MASTER.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/75">Every learner deserves a learning environment that adapts to them — while still keeping expectations, structure and measurable progress clear.</p><button onClick={() => navigate('/contact')} className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3.5 text-sm font-extrabold text-slate-950">Talk to Medora <ArrowRight size={16}/></button></div></div></section>
  </>;
}
