import { ArrowRight, Quote } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { successStories, testimonials } from "../data/content";

const hero = "https://images.pexels.com/photos/16420457/pexels-photo-16420457.jpeg?auto=compress&cs=tinysrgb&w=1800";

export default function SuccessStories() {
  const navigate = useNavigate();
  return <>
    <section className="relative min-h-[68vh] overflow-hidden bg-slate-950 text-white"><img src={hero} alt="Students celebrating learning" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-950/55 to-slate-950/10"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/65 to-transparent"/><div className="relative mx-auto flex min-h-[68vh] max-w-7xl items-end px-4 pb-12 pt-20 sm:px-6 lg:px-8 lg:pb-16"><div className="max-w-3xl reveal-up"><p className="text-[10px] font-black tracking-[.3em] text-cyan-300">SUCCESS STORIES</p><h1 className="mt-4 text-5xl font-black leading-[.96] tracking-[-.04em] sm:text-6xl lg:text-7xl">Progress you can see. Confidence you can feel.</h1><p className="mt-6 max-w-2xl text-sm leading-7 text-white/75 sm:text-base">Real learner journeys across different classes, curriculums and learning models.</p></div></div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-3">{successStories.map(([name, location, course, model, quote, outcomes, image]) => <article key={name} className="group overflow-hidden rounded-[30px] border border-slate-100 bg-slate-50 shadow-card transition hover:-translate-y-1 hover:shadow-soft"><div className="relative h-64 overflow-hidden"><img src={image} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/65 to-transparent"/><div className="absolute bottom-4 left-4 right-4 text-white"><p className="text-[9px] font-black uppercase tracking-widest text-cyan-200">{model}</p><h3 className="mt-1 text-xl font-black">{name}</h3></div></div><div className="p-6"><p className="text-xs font-bold text-blue-700">{course} • {location}</p><p className="mt-4 text-sm leading-7 text-slate-600">“{quote}”</p><div className="mt-5 flex flex-wrap gap-2">{outcomes.map(x => <span key={x} className="rounded-full bg-white px-3 py-1.5 text-[10px] font-bold text-slate-600">{x}</span>)}</div></div></article>)}</div></div></section>
    <section className="bg-gradient-to-br from-blue-50 via-white to-violet-50 py-20"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><div className="text-center"><p className="text-[10px] font-black tracking-[.28em] text-blue-700">PARENT VOICES</p><h2 className="mt-3 text-4xl font-black text-slate-950">What families notice first.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.map(([name, role, location, quote]) => <article key={name} className="rounded-[28px] border border-white bg-white/80 p-6 shadow-sm"><Quote className="text-blue-600" size={24}/><p className="mt-5 text-sm leading-7 text-slate-600">“{quote}”</p><p className="mt-6 text-sm font-black text-slate-900">{name}</p><p className="mt-1 text-[11px] text-slate-400">{role} • {location}</p></article>)}</div><div className="mt-10 flex justify-center"><button onClick={() => navigate('/contact')} className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white hover:bg-blue-700">Start your learner journey <ArrowRight size={16}/></button></div></div></section>
  </>;
}
